//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T марка.
    /// </summary>
    // *** Start programmer edit section *** (tМарка CustomAttributes)

    // *** End programmer edit section *** (tМарка CustomAttributes)
    public enum tМарка
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.Citroen CustomAttributes)

        // *** End programmer edit section *** (tМарка.Citroen CustomAttributes)
        Citroen,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.Daewoo CustomAttributes)

        // *** End programmer edit section *** (tМарка.Daewoo CustomAttributes)
        Daewoo,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.DAF CustomAttributes)

        // *** End programmer edit section *** (tМарка.DAF CustomAttributes)
        DAF,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.FAW CustomAttributes)

        // *** End programmer edit section *** (tМарка.FAW CustomAttributes)
        FAW,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.Ford CustomAttributes)

        // *** End programmer edit section *** (tМарка.Ford CustomAttributes)
        Ford,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (tМарка.GAZ CustomAttributes)

        // *** End programmer edit section *** (tМарка.GAZ CustomAttributes)
        GAZ,
    }
}
