//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Личность.
    /// </summary>
    // *** Start programmer edit section *** (Личность CustomAttributes)

    // *** End programmer edit section *** (Личность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛичностьE", new string[] {
            "Фамилия as \'Фамилия\' on \'-Владелец склада\'",
            "Имя as \'Имя\' on \'-Владелец склада\'",
            "Отчество as \'Отчество\' on \'-Владелец склада\'",
            "Актуально as \'Актуально\'"})]
    [View("ЛичностьL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Актуально as \'Актуально\'"})]
    public class Личность : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private bool fАктуально = true;
        
        // *** Start programmer edit section *** (Личность CustomMembers)

        // *** End programmer edit section *** (Личность CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Личность.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Личность.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Личность.Фамилия Get start)

                // *** End programmer edit section *** (Личность.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Личность.Фамилия Get end)

                // *** End programmer edit section *** (Личность.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Личность.Фамилия Set start)

                // *** End programmer edit section *** (Личность.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Личность.Фамилия Set end)

                // *** End programmer edit section *** (Личность.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Личность.Имя CustomAttributes)

        // *** End programmer edit section *** (Личность.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Личность.Имя Get start)

                // *** End programmer edit section *** (Личность.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Личность.Имя Get end)

                // *** End programmer edit section *** (Личность.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Личность.Имя Set start)

                // *** End programmer edit section *** (Личность.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Личность.Имя Set end)

                // *** End programmer edit section *** (Личность.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Личность.Отчество CustomAttributes)

        // *** End programmer edit section *** (Личность.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Личность.Отчество Get start)

                // *** End programmer edit section *** (Личность.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Личность.Отчество Get end)

                // *** End programmer edit section *** (Личность.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Личность.Отчество Set start)

                // *** End programmer edit section *** (Личность.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Личность.Отчество Set end)

                // *** End programmer edit section *** (Личность.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Личность.Актуально CustomAttributes)

        // *** End programmer edit section *** (Личность.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (Личность.Актуально Get start)

                // *** End programmer edit section *** (Личность.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (Личность.Актуально Get end)

                // *** End programmer edit section *** (Личность.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Личность.Актуально Set start)

                // *** End programmer edit section *** (Личность.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (Личность.Актуально Set end)

                // *** End programmer edit section *** (Личность.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛичностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьE", typeof(Sneg.АСУ_Склад.Личность));
                }
            }
            
            /// <summary>
            /// "ЛичностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьL", typeof(Sneg.АСУ_Склад.Личность));
                }
            }
        }
    }
}
