//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Машина.
    /// </summary>
    // *** Start programmer edit section *** (Машина CustomAttributes)

    // *** End programmer edit section *** (Машина CustomAttributes)
    [BusinessServer("Sneg.АСУ_Склад.МашинаBS, АСУ_Склад.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МашинаE", new string[] {
            "Актуально",
            "Марка as \'Марка\'",
            "Грузоподъемность as \'Грузоподъемность (в тоннах)\'",
            "ВладелецМашины as \'Владелец машины\'",
            "ВладелецМашины.Фамилия as \'Фамилия\' on \'-Владелец машины\'",
            "ВладелецМашины.Имя as \'Имя\' on \'-Владелец машины\'",
            "ВладелецМашины.Отчество as \'Отчество\' on \'-Владелец машины\'"})]
    [MasterViewDefineAttribute("МашинаE", "ВладелецМашины", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("МашинаL", new string[] {
            "Марка as \'Марка\'",
            "ВладелецМашины",
            "Грузоподъемность as \'Грузоподъемность\'",
            "ВладелецМашины.Фамилия as \'Фамилия владельца\'",
            "ВладелецМашины.Имя as \'Имя владельца\'",
            "ВладелецМашины.Отчество as \'Отчество валдельца\'",
            "Актуально"} , Hidden = new string[] { "ВладелецМашины"})]
    public class Машина : ICSSoft.STORMNET.DataObject
    {
        
        private Sneg.АСУ_Склад.tМарка fМарка;
        
        private decimal fГрузоподъемность;
        
        private bool fАктуально = true;
        
        private Sneg.АСУ_Склад.Личность fВладелецМашины;
        
        // *** Start programmer edit section *** (Машина CustomMembers)

        // *** End programmer edit section *** (Машина CustomMembers)

        
        /// <summary>
        /// Марка.
        /// </summary>
        // *** Start programmer edit section *** (Машина.Марка CustomAttributes)

        // *** End programmer edit section *** (Машина.Марка CustomAttributes)
        [NotNull()]
        public virtual Sneg.АСУ_Склад.tМарка Марка
        {
            get
            {
                // *** Start programmer edit section *** (Машина.Марка Get start)

                // *** End programmer edit section *** (Машина.Марка Get start)
                Sneg.АСУ_Склад.tМарка result = this.fМарка;
                // *** Start programmer edit section *** (Машина.Марка Get end)

                // *** End programmer edit section *** (Машина.Марка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Машина.Марка Set start)

                // *** End programmer edit section *** (Машина.Марка Set start)
                this.fМарка = value;
                // *** Start programmer edit section *** (Машина.Марка Set end)

                // *** End programmer edit section *** (Машина.Марка Set end)
            }
        }
        
        /// <summary>
        /// Грузоподъемность.
        /// </summary>
        // *** Start programmer edit section *** (Машина.Грузоподъемность CustomAttributes)

        // *** End programmer edit section *** (Машина.Грузоподъемность CustomAttributes)
        public virtual decimal Грузоподъемность
        {
            get
            {
                // *** Start programmer edit section *** (Машина.Грузоподъемность Get start)

                // *** End programmer edit section *** (Машина.Грузоподъемность Get start)
                decimal result = this.fГрузоподъемность;
                // *** Start programmer edit section *** (Машина.Грузоподъемность Get end)

                // *** End programmer edit section *** (Машина.Грузоподъемность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Машина.Грузоподъемность Set start)

                // *** End programmer edit section *** (Машина.Грузоподъемность Set start)
                this.fГрузоподъемность = value;
                // *** Start programmer edit section *** (Машина.Грузоподъемность Set end)

                // *** End programmer edit section *** (Машина.Грузоподъемность Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Машина.Актуально CustomAttributes)

        // *** End programmer edit section *** (Машина.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (Машина.Актуально Get start)

                // *** End programmer edit section *** (Машина.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (Машина.Актуально Get end)

                // *** End programmer edit section *** (Машина.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Машина.Актуально Set start)

                // *** End programmer edit section *** (Машина.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (Машина.Актуально Set end)

                // *** End programmer edit section *** (Машина.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Машина.
        /// </summary>
        // *** Start programmer edit section *** (Машина.ВладелецМашины CustomAttributes)

        // *** End programmer edit section *** (Машина.ВладелецМашины CustomAttributes)
        [PropertyStorage(new string[] {
                "ВладелецМашины"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Личность ВладелецМашины
        {
            get
            {
                // *** Start programmer edit section *** (Машина.ВладелецМашины Get start)

                // *** End programmer edit section *** (Машина.ВладелецМашины Get start)
                Sneg.АСУ_Склад.Личность result = this.fВладелецМашины;
                // *** Start programmer edit section *** (Машина.ВладелецМашины Get end)

                // *** End programmer edit section *** (Машина.ВладелецМашины Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Машина.ВладелецМашины Set start)

                // *** End programmer edit section *** (Машина.ВладелецМашины Set start)
                this.fВладелецМашины = value;
                // *** Start programmer edit section *** (Машина.ВладелецМашины Set end)

                // *** End programmer edit section *** (Машина.ВладелецМашины Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МашинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МашинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МашинаE", typeof(Sneg.АСУ_Склад.Машина));
                }
            }
            
            /// <summary>
            /// "МашинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МашинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МашинаL", typeof(Sneg.АСУ_Склад.Машина));
                }
            }
        }
    }
}
