//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поступления.
    /// </summary>
    // *** Start programmer edit section *** (Поступления CustomAttributes)

    // *** End programmer edit section *** (Поступления CustomAttributes)
    [BusinessServer("Sneg.АСУ_Склад.ПоступленияBS, АСУ_Склад.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоступленияE", new string[] {
            "Актуально as \'Актуально\'",
            "Дата as \'Дата\'",
            "Количество as \'Количество (в тоннах)\'",
            "Склад",
            "Товар",
            "Машина"})]
    [MasterViewDefineAttribute("ПоступленияE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ПоступленияE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ПоступленияE", "Машина", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Марка")]
    [View("ПоступленияL", new string[] {
            "Дата",
            "Количество as \'Количество\'",
            "Склад.Название",
            "Товар.Название",
            "Машина.Марка",
            "Актуально as \'Актуально\'"})]
    public class Поступления : ICSSoft.STORMNET.DataObject
    {
        
        private decimal fКоличество;
        
        private System.DateTime fДата;
        
        private bool fАктуально = true;
        
        private Sneg.АСУ_Склад.Склад fСклад;
        
        private Sneg.АСУ_Склад.Товар fТовар;
        
        private Sneg.АСУ_Склад.Машина fМашина;
        
        // *** Start programmer edit section *** (Поступления CustomMembers)

        // *** End programmer edit section *** (Поступления CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Количество CustomAttributes)

        // *** End programmer edit section *** (Поступления.Количество CustomAttributes)
        public virtual decimal Количество
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Количество Get start)

                // *** End programmer edit section *** (Поступления.Количество Get start)
                decimal result = this.fКоличество;
                // *** Start programmer edit section *** (Поступления.Количество Get end)

                // *** End programmer edit section *** (Поступления.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Количество Set start)

                // *** End programmer edit section *** (Поступления.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Поступления.Количество Set end)

                // *** End programmer edit section *** (Поступления.Количество Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Дата CustomAttributes)

        // *** End programmer edit section *** (Поступления.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Дата Get start)

                // *** End programmer edit section *** (Поступления.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Поступления.Дата Get end)

                // *** End programmer edit section *** (Поступления.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Дата Set start)

                // *** End programmer edit section *** (Поступления.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Поступления.Дата Set end)

                // *** End programmer edit section *** (Поступления.Дата Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Актуально CustomAttributes)

        // *** End programmer edit section *** (Поступления.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Актуально Get start)

                // *** End programmer edit section *** (Поступления.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (Поступления.Актуально Get end)

                // *** End programmer edit section *** (Поступления.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Актуально Set start)

                // *** End programmer edit section *** (Поступления.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (Поступления.Актуально Set end)

                // *** End programmer edit section *** (Поступления.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Поступления.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Склад CustomAttributes)

        // *** End programmer edit section *** (Поступления.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Склад Get start)

                // *** End programmer edit section *** (Поступления.Склад Get start)
                Sneg.АСУ_Склад.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Поступления.Склад Get end)

                // *** End programmer edit section *** (Поступления.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Склад Set start)

                // *** End programmer edit section *** (Поступления.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Поступления.Склад Set end)

                // *** End programmer edit section *** (Поступления.Склад Set end)
            }
        }
        
        /// <summary>
        /// Поступления.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Товар CustomAttributes)

        // *** End programmer edit section *** (Поступления.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Товар Get start)

                // *** End programmer edit section *** (Поступления.Товар Get start)
                Sneg.АСУ_Склад.Товар result = this.fТовар;
                // *** Start programmer edit section *** (Поступления.Товар Get end)

                // *** End programmer edit section *** (Поступления.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Товар Set start)

                // *** End programmer edit section *** (Поступления.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (Поступления.Товар Set end)

                // *** End programmer edit section *** (Поступления.Товар Set end)
            }
        }
        
        /// <summary>
        /// Поступления.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Машина CustomAttributes)

        // *** End programmer edit section *** (Поступления.Машина CustomAttributes)
        [PropertyStorage(new string[] {
                "Машина"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Машина Машина
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Машина Get start)

                // *** End programmer edit section *** (Поступления.Машина Get start)
                Sneg.АСУ_Склад.Машина result = this.fМашина;
                // *** Start programmer edit section *** (Поступления.Машина Get end)

                // *** End programmer edit section *** (Поступления.Машина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Машина Set start)

                // *** End programmer edit section *** (Поступления.Машина Set start)
                this.fМашина = value;
                // *** Start programmer edit section *** (Поступления.Машина Set end)

                // *** End programmer edit section *** (Поступления.Машина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоступленияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоступленияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоступленияE", typeof(Sneg.АСУ_Склад.Поступления));
                }
            }
            
            /// <summary>
            /// "ПоступленияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоступленияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоступленияL", typeof(Sneg.АСУ_Склад.Поступления));
                }
            }
        }
    }
}
