//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [BusinessServer("Sneg.АСУ_Склад.ТоварBS, АСУ_Склад.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Актуально as \'Актуально\'",
            "Номер as \'Номер\'",
            "Название as \'Название\'"})]
    [View("ТоварL", new string[] {
            "Номер as \'Номер\'",
            "Название as \'Название\'",
            "Актуально as \'Актуально\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fНазвание;
        
        private bool fАктуально = true;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Номер CustomAttributes)

        // *** End programmer edit section *** (Товар.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Номер Get start)

                // *** End programmer edit section *** (Товар.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Товар.Номер Get end)

                // *** End programmer edit section *** (Товар.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Номер Set start)

                // *** End programmer edit section *** (Товар.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Товар.Номер Set end)

                // *** End programmer edit section *** (Товар.Номер Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// Актуально.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Актуально CustomAttributes)

        // *** End programmer edit section *** (Товар.Актуально CustomAttributes)
        public virtual bool Актуально
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Актуально Get start)

                // *** End programmer edit section *** (Товар.Актуально Get start)
                bool result = this.fАктуально;
                // *** Start programmer edit section *** (Товар.Актуально Get end)

                // *** End programmer edit section *** (Товар.Актуально Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Актуально Set start)

                // *** End programmer edit section *** (Товар.Актуально Set start)
                this.fАктуально = value;
                // *** Start programmer edit section *** (Товар.Актуально Set end)

                // *** End programmer edit section *** (Товар.Актуально Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(Sneg.АСУ_Склад.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(Sneg.АСУ_Склад.Товар));
                }
            }
        }
    }
}
