<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Zapros.aspx.cs" Inherits="Sneg.АСУ_Склад.Zapros" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Перечислить владельцев машин, привозящих товар на конкретный склад</h2>
    <asp:TextBox runat="server" ID="ctrlWarehouse" Text="Склад"></asp:TextBox>
    <asp:Button runat="server" ID="ctrlFind" Text="Найти"/>
    

    <asp:DataList ID="ctrlList"
        BorderColor="Black"
        BorderWidth="2px"
        BorderStyle="Solid"
        CellPadding="5"
        CellSpacing="5"
        RepeatDirection="Vertical"
        RepeatLayout="Table"
        runat="server" >

        <HeaderTemplate>
            <b>Владельцы</b>
        </HeaderTemplate>
        <ItemTemplate>            
            <asp:Label Text='<%# Eval("Фамилия")%>' runat="server" />
        </ItemTemplate>
    </asp:DataList>
     
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
