//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.Business.LINQProvider;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;    
    using System.Data;
    using System.Linq;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЛичностьBS.
    /// </summary>
    // *** Start programmer edit section *** (ЛичностьBS CustomAttributes)

    // *** End programmer edit section *** (ЛичностьBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЛичностьBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ЛичностьBS CustomMembers)

        // *** End programmer edit section *** (ЛичностьBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateЛичность CustomAttributes)

        // *** End programmer edit section *** (OnUpdateЛичность CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateЛичность(Sneg.АСУ_Склад.Личность UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateЛичность)
            if (UpdatedObject.GetStatus() == ObjectStatus.Deleted)
            {
                UpdatedObject.LockObject(UpdatedObject);
                UpdatedObject.SetStatus(ObjectStatus.Altered);
                UpdatedObject.Актуально = false;
                
                var carList = ((SQLDataService)DataService).Query<Машина>(Машина.Views.МашинаL).Where(k => k.ВладелецМашины.__PrimaryKey == UpdatedObject.__PrimaryKey).ToArray();
                foreach(var car in carList)
                {
                    car.SetStatus(ObjectStatus.Deleted);
                }
                var whList = ((SQLDataService)DataService).Query<Склад>(Склад.Views.СкладL).Where(k => k.ВладелецСклада.__PrimaryKey == UpdatedObject.__PrimaryKey).ToArray();
                foreach (var wh in whList)
                {
                    wh.SetStatus(ObjectStatus.Deleted);
                }
                return carList;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateЛичность)
        }
    }
}
