//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// МашинаBS.
    /// </summary>
    // *** Start programmer edit section *** (МашинаBS CustomAttributes)

    // *** End programmer edit section *** (МашинаBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class МашинаBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (МашинаBS CustomMembers)

        // *** End programmer edit section *** (МашинаBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateМашина CustomAttributes)

        // *** End programmer edit section *** (OnUpdateМашина CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateМашина(Sneg.АСУ_Склад.Машина UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateМашина)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateМашина)
        }
    }
}
