//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System;
    using System.Linq;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// МашинаBS.
    /// </summary>
    // *** Start programmer edit section *** (МашинаBS CustomAttributes)

    // *** End programmer edit section *** (МашинаBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class МашинаBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (МашинаBS CustomMembers)

        // *** End programmer edit section *** (МашинаBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateМашина CustomAttributes)

        // *** End programmer edit section *** (OnUpdateМашина CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateМашина(Sneg.АСУ_Склад.Машина UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateМашина)
            if (UpdatedObject.GetStatus() == ObjectStatus.Deleted)
            {
                DataService.LoadObject(UpdatedObject);                
                UpdatedObject.SetStatus(ObjectStatus.Altered);
                UpdatedObject.Актуально = false;

                var supplyList = ((SQLDataService)DataService).Query<Поступления>(Поступления.Views.ПоступленияL).Where(k => k.Машина.__PrimaryKey == UpdatedObject.__PrimaryKey).ToArray();
                foreach (var supply in supplyList)
                {
                    supply.SetStatus(ObjectStatus.Deleted);
                }
                return supplyList;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateМашина)
        }
    }
}
