//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поступления BS.
    /// </summary>
    // *** Start programmer edit section *** (ПоступленияBS CustomAttributes)

    // *** End programmer edit section *** (ПоступленияBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ПоступленияBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ПоступленияBS CustomMembers)

        // *** End programmer edit section *** (ПоступленияBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateПоступления CustomAttributes)

        // *** End programmer edit section *** (OnUpdateПоступления CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateПоступления(Sneg.АСУ_Склад.Поступления UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateПоступления)
            if(UpdatedObject.GetStatus() == ObjectStatus.Deleted)
            {
                UpdatedObject.LockObject(UpdatedObject);
                UpdatedObject.SetStatus(ObjectStatus.Altered);
                UpdatedObject.Актуально = false;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateПоступления)
        }
    }
}
