//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СкладBS.
    /// </summary>
    // *** Start programmer edit section *** (СкладBS CustomAttributes)

    // *** End programmer edit section *** (СкладBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СкладBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (СкладBS CustomMembers)

        // *** End programmer edit section *** (СкладBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateСклад CustomAttributes)

        // *** End programmer edit section *** (OnUpdateСклад CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateСклад(Sneg.АСУ_Склад.Склад UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateСклад)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateСклад)
        }
    }
}
