//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТоварНаСкладеBS.
    /// </summary>
    // *** Start programmer edit section *** (ТоварНаСкладеBS CustomAttributes)

    // *** End programmer edit section *** (ТоварНаСкладеBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТоварНаСкладеBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ТоварНаСкладеBS CustomMembers)

        // *** End programmer edit section *** (ТоварНаСкладеBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateТоварНаСкладе CustomAttributes)

        // *** End programmer edit section *** (OnUpdateТоварНаСкладе CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateТоварНаСкладе(Sneg.АСУ_Склад.ТоварНаСкладе UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateТоварНаСкладе)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateТоварНаСкладе)
        }
    }
}
