//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТоварBS.
    /// </summary>
    // *** Start programmer edit section *** (ТоварBS CustomAttributes)

    // *** End programmer edit section *** (ТоварBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТоварBS : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (ТоварBS CustomMembers)

        // *** End programmer edit section *** (ТоварBS CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateТовар CustomAttributes)

        // *** End programmer edit section *** (OnUpdateТовар CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateТовар(Sneg.АСУ_Склад.Товар UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateТовар)
            if (UpdatedObject.GetStatus() == ObjectStatus.Deleted)
            {
                DataService.LoadObject(UpdatedObject);
                UpdatedObject.SetStatus(ObjectStatus.Altered);
                UpdatedObject.Актуально = false;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateТовар)
        }
    }
}
