<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="MashinaE.aspx.cs" Inherits="Sneg.АСУ_Склад.МашинаE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Машина</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<asp:ValidationSummary ID="ValidationSummary1" runat="server" ValidationGroup="savedoc" />
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlАктуальноLabel" runat="server" Text="Актуально" EnableViewState="False">
</asp:Label>
<asp:CheckBox ID="ctrlАктуально" CssClass="descTxt" runat="server" Text=""/>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlМаркаLabel" runat="server" Text="Марка" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlМарка" CssClass="descTxt" runat="server">
	<asp:ListItem>Citroen</asp:ListItem>
<asp:ListItem>Daewoo</asp:ListItem>
<asp:ListItem>DAF</asp:ListItem>
<asp:ListItem>FAW</asp:ListItem>
<asp:ListItem>Ford</asp:ListItem>
<asp:ListItem>GAZ</asp:ListItem>

</asp:DropDownList>
<asp:RequiredFieldValidator ID="ctrlМаркаRequiredFieldValidator" runat="server" ControlToValidate="ctrlМарка"
                            ErrorMessage="Не указано: Марка" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlГрузоподъемностьLabel" runat="server" Text="Грузоподъемность (в тоннах)" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox CssClass="descTxt" ID="ctrlГрузоподъемность" runat="server">
</ac:DecimalTextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВладелецМашиныLabel" runat="server" Text="Владелец машины" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlВладелецМашины" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlВладелецМашиныRequiredFieldValidator" runat="server" ControlToValidate="ctrlВладелецМашины"
                            ErrorMessage="Не указано: ВладелецМашины" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<fieldset ID="ctrl_fsВладелец_машины" style="clear: left">
	<legend>Владелец машины</legend>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВладелецМашины_ФамилияLabel" runat="server" Text="Фамилия" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlВладелецМашины_Фамилия" runat="server" ReadOnly="true">
</asp:TextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВладелецМашины_ИмяLabel" runat="server" Text="Имя" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlВладелецМашины_Имя" runat="server" ReadOnly="true">
</asp:TextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВладелецМашины_ОтчествоLabel" runat="server" Text="Отчество" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlВладелецМашины_Отчество" runat="server" ReadOnly="true">
</asp:TextBox>


</div>

</fieldset>
</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
